//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_proba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otpad
    {
        public int Id { get; set; }
        public string Ulica { get; set; }
        public string Grad { get; set; }
        public string VrstaOtpada { get; set; }
        public string Pon { get; set; }
        public string Uto { get; set; }
        public string Sri { get; set; }
        public string Cet { get; set; }
        public string Pet { get; set; }
        public string Sub { get; set; }
        public string Ned { get; set; }
    }
}
